#!/bin/python3

import sys


n = float(input())
lst = [int(x) for x in input().split()]
print (len([x for x in lst if x > 0])/n)
print (len([x for x in lst if x < 0])/n)
print (len([x for x in lst if x == 0])/n)
