#!/bin/python3

import sys

n, k, m = map(int, input().strip().split())
arr = list(map(int, input().strip().split()))
k = k%n
arr = arr[-k:] + arr[:-k]
for i in range(m):
    print(arr[int(input().strip())])
