#!/bin/python3

import sys


n = int(input().strip())
arr = [int(arr_temp) for arr_temp in input().strip().split(' ')]

temp = n

while temp > 0:
    tempMin = min(arr)
    print(len(arr))
    
    for i in range(len(arr)):
        arr[i] = arr[i] - tempMin
        if arr[i] <= 0:
            arr[i]=0
        
    for i in range(arr.count(0)):
        arr.remove(0)
