#!/bin/python3

import sys

size = [int(i) for i in input().split()]
#The function ord returns unicode code point for character. Unicode is superset of ASCII. It basically returns ASCII here.
word = [size[ord(c)-ord('a')] for c in input()]
print(max(word)*len(word))
