#!/bin/python3
n = int(input())
a = []
for _ in range(n):
    a_1 = int(input())
    a.append(a_1)
    
for i in range(n):
    if a[i] >= 38:
        if a[i]%5 > 2:
            a[i] = a[i] + (5-a[i]%5)
        else:
            a[i] = a[i]
    else:
        a[i] = a[i]
for i in range(n):
    print(a[i])
