#!/bin/python3

import sys
import math


n = int(input().strip())
A = [int(A_temp) for A_temp in input().strip().split(' ')]

min_val = sys.maxsize

dict = {}
# create the dictionary as
# key = position of elements in A
# value = location i's value in A
for i in range(len(A)):
    dict[i] = A[i]

# sort dictionary on value
dict = sorted(dict.items(), key=lambda x: x[1])

# check key value distance on every 2 elements
for i in range(len(dict)):
    # dict[i][0] -> key
    # dict[i][1] -> value
    if i+1 < len(dict):
        if dict[i][1]==dict[i+1][1]:
            min_val = min(min_val,abs(dict[i][0]-dict[i+1][0]))
            
            
if min_val == sys.maxsize:
    print("-1")
else:
    print(min_val)
